name: Daily Scrape

# Run the workflow daily
on:
  schedule:
    - cron: "0 * * * *" 

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r src/scripts/requirements.txt  # Assumes you have a requirements.txt file

    # Step 4: Run the Python scraping script
    - name: Run scraping script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
      run: |
        source .venv/bin/activate
        python src/scripts/snapshot_crawler.py
